--1.
db.language.aggregate([
    {
        $lookup:{
            from:"film",
            localField:"_id",
            foreignField:"language_id",
            as:"film"
        }
    },
    {
        $unwind:"$film"
    },
    {
        $group:{
            _id:"$name",
            count:{$sum:1}
        }
    }
]
).sort({count:-1})

--2 
db.actor.aggregate([
    {
        $lookup:{
            from:"film_actor",
            localField:"_id",
            foreignField:"actor_id",
            as:"film_actor"
        }
    },
    {
        $unwind:"$film_actor"    
    },
    {
        $group:{
            first_name:"$first_name",
            last_name:"$last_name",
            count:{$sum:1}
        }
    }
])